# Generated by Django 4.2.6 on 2023-11-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="video_link",
            field=models.TextField(),
        ),
    ]
