# Generated by Django 4.2.6 on 2023-11-06 12:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_remove_project_image_project_year"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProjectsImage",
            new_name="ProjectImage",
        ),
    ]
