# Generated by Django 4.2.6 on 2023-11-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0002_customer_city"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="english_name",
        ),
        migrations.AddField(
            model_name="customer",
            name="persian_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
