# Generated by Django 4.2.6 on 2023-10-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descriptions",
            field=models.ManyToManyField(to="products.description"),
        ),
    ]
