# Generated by Django 4.2.6 on 2023-10-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_remove_description_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
