# Generated by Django 4.2.6 on 2023-10-30 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_description_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="preamble",
            field=models.TextField(null=True),
        ),
    ]
