# Generated by Django 4.2.6 on 2023-10-30 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_product_preamble"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="preamble",
            field=models.TextField(),
        ),
    ]
