# Generated by Django 4.2.6 on 2023-10-30 10:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0007_brand_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="preamble",
            field=models.TextField(null=True),
        ),
    ]
