# Generated by Django 4.2.6 on 2023-10-30 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0009_alter_brand_preamble"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="description",
            name="products",
        ),
        migrations.RemoveField(
            model_name="product",
            name="descriptions",
        ),
        migrations.AddField(
            model_name="description",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.product",
            ),
        ),
    ]
