# Generated by Django 4.2.6 on 2023-10-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0010_remove_description_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="description",
            name="product",
        ),
        migrations.AddField(
            model_name="description",
            name="products",
            field=models.ManyToManyField(to="products.product"),
        ),
    ]
