# Generated by Django 4.2.6 on 2023-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0011_remove_description_product_description_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="description",
            name="products",
            field=models.ManyToManyField(
                related_name="descriptions", to="products.product"
            ),
        ),
    ]
