# Generated by Django 4.2.6 on 2023-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0012_alter_description_products"),
    ]

    operations = [
        migrations.CreateModel(
            name="Carousel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("title", models.CharField(max_length=256)),
                ("image", models.ImageField(upload_to="")),
            ],
        ),
    ]
