# Generated by Django 4.2.6 on 2023-10-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0013_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="carousel",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="carousel",
            name="title",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
