# Generated by Django 4.2.6 on 2023-11-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0014_carousel_name_alter_carousel_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategorylevel1",
            name="image",
            field=models.ImageField(null=True, upload_to=""),
        ),
    ]
