# Generated by Django 4.2.6 on 2023-11-06 08:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0016_banners_productcategorylevel1_banner"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Banners",
            new_name="Banner",
        ),
    ]
