# Generated by Django 4.2.6 on 2023-11-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0019_rename_image_brand_image_large_brand_image_small"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="carousel",
            field=models.BooleanField(null=True),
        ),
    ]
