# Generated by Django 4.2.6 on 2023-11-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0021_alter_productcategorylevel1_banner_delete_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="productType",
            field=models.CharField(
                choices=[("Pt", "PART"), ("Sr", "SERVICE"), ("Cl", "CLASS")],
                default="Pt",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="carousel",
            field=models.BooleanField(default=False),
        ),
    ]
