# Generated by Django 4.2.6 on 2023-11-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0022_product_producttype_alter_product_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcategorylevel1",
            name="productType",
            field=models.CharField(
                choices=[("Pt", "PART"), ("Sr", "SERVICE"), ("Cl", "CLASS")],
                default="Pt",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="productcategorylevel2",
            name="productType",
            field=models.CharField(
                choices=[("Pt", "PART"), ("Sr", "SERVICE"), ("Cl", "CLASS")],
                default="Pt",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="productcategorylevel3",
            name="productType",
            field=models.CharField(
                choices=[("Pt", "PART"), ("Sr", "SERVICE"), ("Cl", "CLASS")],
                default="Pt",
                max_length=255,
            ),
        ),
    ]
