# Generated by Django 4.2.6 on 2023-11-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0024_remove_brand_slug_remove_product_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcategorylevel1",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
