# Generated by Django 4.2.6 on 2023-11-08 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0026_remove_product_image_productvideo_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
