# Generated by Django 4.2.6 on 2023-11-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0027_product_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Carousel",
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
