# Generated by Django 4.2.6 on 2023-11-08 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0028_delete_carousel_alter_product_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="description",
            name="field",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="productcategorylevel1",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productcategorylevel2",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productcategorylevel3",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="productvideo",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="field",
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name="specification",
            name="field",
            field=models.TextField(unique=True),
        ),
    ]
